import type { Metadata } from 'next';
import '@wevisdemo/ui/styles/index.css';
import '../styles/globals.css';
import AppNavbar from '@/components/AppNavbar';
import { Providers } from './providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang='en'
      className='wv-ibmplex text-center'
    >
      <body className='overflow-x-hidden'>
        <Providers>
          <AppNavbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
