import type { Metadata } from 'next';
import './globals.css';
import { twMerge } from 'tailwind-merge';
import { bodyFont, headerFont } from './fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang='en'
      className={twMerge(
        headerFont.variable,
        bodyFont.variable,
        'bg-black text-white'
      )}
    >
      <body className='bg-black text-white'>{children}</body>
    </html>
  );
}
